spring:
  port: 8080
  jacksonproperty-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
      path: /h2-console
      #settings.trace: false
      settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: spaceFan
    password: spaceFan
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # as we use flyway we disable automatic creation (otherwise ddl auto is post flyway)
      ddl-auto: none

  flyway:
    user: spaceFan
    password: spaceFan
    #enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always