spring:
  port: 8080
  jacksonproperty-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
      path: /h2-console
      #settings.trace: false
      settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: spaceFan
    password: spaceFan
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # as we use flyway we disable automatic creation (otherwise ddl auto is post flyway)
      ddl-auto: none

  flyway:
    user: spaceFan
    password: spaceFan
    #enabled: false
  asciidoctor:
    enabled: true
    source-docs: src/main/asciidoc
    backend: html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  enable-native-support: true
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO