CREATE TABLE IF NOT EXISTS `ACCOUNT` (
    `ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USER_ID`  int NOT NULL,
    `CURRENCY_CODE` CHAR(3) NOT NULL,
    `BALANCE` DECIMAL(18,2) NOT NULL CHECK (BALANCE > 0),
    `AMOUNT_TYPE` CHAR(1) NOT NULL,
    `CREATED_ON` timestamp,
    `LAST_UPDATED_ON` timestamp,
     FOREIGN KEY (`USER_ID`) REFERENCES `CUSTOMER` (`ID`)
);


/*
Not using hibernate auto_ddl
*/
CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;