CREATE TABLE IF NOT EXISTS `MOVEMENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ACCOUNT_ID` BIGINT NOT NULL,
    `TO_ACCOUNT_ID` BIGINT NOT NULL,
    `AMOUNT` DECIMAL(18,2) NOT NULL CHECK (AMOUNT >= 0),
    `CURRENCY_CODE` CHAR(3) NOT NULL,
    `MOVEMENT_TYPE` CHAR(6) NOT NULL,
    `STATUS` VARCHAR(10) NOT NULL,
    `ORDERED_ON` timestamp,
    `CREATED_ON` timestamp,
    `LAST_UPDATED_ON` timestamp,
     FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ID`),
     FOREIGN KEY (`TO_ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ID`)
);

ALTER TABLE MOVEMENT ADD CONSTRAINT unique_movement_transaction UNIQUE (ACCOUNT_ID, TO_ACCOUNT_ID, ORDERED_ON);

/*
Not using hibernate auto_ddl
*/
CREATE SEQUENCE MOVEMENT_SEQ START WITH 1 INCREMENT BY 1;