CREATE TABLE ACCOUNT_CONTRIBUTOR (
  ACCOUNT_ID BIGINT NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL,
  AMOUNT DOUBLE NOT NULL CHECK (AMOUNT >= 0),
  PRIMARY KEY (ACCOUNT_ID, CUSTOMER_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
  `CREATED_ON` timestamp,
  `LAST_UPDATED_ON` timestamp
);


/*
Not using hibernate auto_ddl
*/
CREATE SEQUENCE ACCOUNT_CONTRIBUTOR_SEQ START WITH 1 INCREMENT BY 1;